name: Build and Release Rust Binaries

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
          - target: aarch64-unknown-linux-gnu
          - target: x86_64-pc-windows-gnu
          - target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Swatinem Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Install APT dependencies with cache
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential gcc-multilib

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Extract metadata
        id: vars
        run: |
          hash=$(git rev-parse --short HEAD)
          date=$(git log -1 --date=format:'%Y%m%d' --format='%ad')
          echo "tag=dbussy-$hash-$date" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          name: ${{ steps.vars.outputs.tag }}
          files: |
            **/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

